# Generated by Django 3.0.8 on 2020-07-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropBox',
            fields=[
                ('Fileid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dbfile', models.FileField(upload_to='')),
            ],
        ),
    ]
